version: '3'

services:
   tb3_simulation_client:
     container_name: tb3_simulation_client_c
     image: ros1_turtlebot3_rest_api:latest
     volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix:/tmp/.X11-unix
       - ./rviz/test.rviz:/home/ubuntu/catkin_ws/src/nav_rest_api_turtlebot/rviz/test.rviz
     environment:
       DISPLAY: $DISPLAY
       TURTLEBOT3_MODEL: burger
     network_mode: "host"
     command: roslaunch nav_rest_api_turtlebot test.launch show_rviz_gazebo:=true
