version: '3'

services:
   tb3_simulation_client:
     container_name: tb3_simulation_client_c
     image: ros1_turtlebot3_rest_api:latest
     volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
     environment:
       DISABLE_ROS1_EOL_WARNINGS: 1
       DISPLAY: $DISPLAY
       TURTLEBOT3_MODEL: waffle
     network_mode: "host"
     command: roslaunch nav_rest_api_turtlebot test.launch show_rviz_gazebo:=true